version: 0.2
phases:
  install: 
    runtime-versions:
      golang: latest

  pre_build: 
    commands:
      - go test

  build:
    commands:
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml